# Generated by Django 2.0 on 2021-06-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_auto_20210628_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='csrfmiddlewaretoken',
            field=models.TextField(default='NULL', verbose_name='Токен'),
            preserve_default=False,
        ),
    ]
