# Generated by Django 2.0 on 2021-06-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_news_csrfmiddlewaretoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='csrfmiddlewaretoken',
            new_name='csrf_token',
        ),
    ]
