# Generated by Django 2.0 on 2021-06-29 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_auto_20210629_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 17, 26, 52, 521081), verbose_name='Время публикации новости'),
        ),
    ]
