# Generated by Django 2.0 on 2021-06-29 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0008_auto_20210629_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2021, 6, 29), verbose_name='Date'),
        ),
    ]
