# Generated by Django 2.0 on 2021-06-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0010_auto_20210629_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(blank=True, to='NewsApp.Tag'),
        ),
    ]
